---
title: "TidyTuesday 30-01-24 Groundhog Day"
author: "Dr Richard Clarke"
format: html
editor: source
editor_options: 
  chunk_output_type: console
---

```{r, packages}
library(tidyverse)
library(broom)
```

```{r, reading in data}
groundhogs <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-01-30/groundhogs.csv')
predictions <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-01-30/predictions.csv')

full_data <- left_join(groundhogs, predictions, by = "id") 
```

```{r, converting the latitude variable and selecting data for analysis}

full_data <- full_data %>%
  mutate(lat = case_when(
    latitude < 35 ~ "Lower than 35",
    latitude >= 35 & latitude < 40 ~ "35 - 40",
    latitude >= 40 & latitude < 45 ~ "40 - 45",
    latitude >= 45 & latitude < 50 ~ "45 - 50",
    latitude >= 50 ~ "Higher than 50",
    TRUE ~ "Other"))

analysis_data <- full_data %>%
  filter(!is.na(shadow)) %>%
  mutate(shadow = relevel(as.factor(shadow), ref = "FALSE"),
         lat = relevel(as.factor(lat), ref = "40 - 45")) 

```

```{r, running model and wrangling data for the forest plot}
model_tidy <- glm(shadow ~ lat, 
              data = analysis_data,
              family = binomial) %>%
  tidy(conf.int = TRUE, exponentiate = TRUE)

forest_plot_data <- model_tidy %>%
  select(term, estimate, conf.low, conf.high) %>%
  filter(term != "(Intercept)")%>%
  add_row(term = "Reference (40 - 45)", estimate = 1, conf.low = NA, conf.high = NA) %>%
  mutate(term = recode(term,
                       "latLower than 35" = "Lower than 35 (N=79)",
                       "lat35 - 40" = "35 - 40 (N=343)",
                       "Reference (40 - 45)" = "Reference: 40 - 45 (N=899)",
                       "lat45 - 50" = "45 - 50 (N=91)",
                       "latHigher than 50" = "Higher than 50 (N=50)"))

forest_plot_data <- forest_plot_data %>%
  mutate(term = factor(term, levels = c("Lower than 35 (N=79)", 
                                        "35 - 40 (N=343)", 
                                        "Reference: 40 - 45 (N=899)", 
                                        "45 - 50 (N=91)", 
                                        "Higher than 50 (N=50)")))

```

```{r, creating the forest plot}
plot1 <- forest_plot_data %>%
  ggplot(aes(x = term, y = estimate, ymin = conf.low, ymax = conf.high)) +
  geom_point(size = 3, color = "darkblue") +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2, color = "darkblue") +
  geom_hline(yintercept = 1, linetype = "dashed", color = "red", size = 0.5) +
  coord_flip() +
  xlab("Latitude") +
  ylab("Odds Ratio (95% CI)") +
  ggtitle("Effect of Latitude on Shadow Presence") + 
  theme_minimal(base_size = 14) +
  theme(plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
    axis.text.y = element_text(size = 12),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    plot.margin = margin(10, 50, 10, 20),
    plot.background = element_rect(fill = "white", colour = NA))

ggsave("TidyTuesday 30-01-24 Groundhog Day.png", plot = plot1, width = 7.37, height = 5.56, dpi = 300)


```